### ISSUE TITLE
Support libarchive 3.2.1

### ISSUE THREAD

**Issue by domenkozar** [matejc/tarman#24]
Due to newer libarchive, tarman doesn't build anymore on NixOS 16.09

cc @matejc

**Comment by matejc** [comment]
thanks for reporting but this is a NixOS/nixpkgs problem, we have packaged `libarchive 3.2.1`. `python-libarchive 3.1.2-1` supports only `libarchive 3.1.2`. `python-libarchive 3.1.2-1` is the latest. therefore we have to add new package to nixpkgs: `libarchive 3.1.2`
